[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]
ffi = true

[etherscan]
mainnet = { key = "${https://eth-mainnet.g.alchemy.com/v2/uFo06ZRC8R4kJWqVirGIcFPdOB0_x84c}" }
sepolia = { key = "${https://eth-sepolia.g.alchemy.com/v2/bjeluV4S5sSTo-Ck-LF4_K__8V9MP4ke}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
